# Where things are
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

defaults:
- scope:
path: ""
type: "people"
values:
layout: "people"
- scope:
path: ""
type: "posts"
values:
layout: "post"
- scope:
path: ""
values:
layout: "default"

plugins:
- jekyll-sitemap