# Where things are
source: .
destination: ./_site
collections_dir: .
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass
collections:
  authors:
    output: true

defaults:
- scope:
path: ""
type: "people"
values:
layout: "people"
- scope:
path: ""
type: "posts"
values:
layout: "post"
- scope:
path: ""
values:
layout: "default"

plugins:
- jekyll-sitemap