name: Songyan website
description: Songyan Yu's research interests
collections:
  authors:
    output: true

defaults:
-scope:
path: ""
type: "people"
values:
layout: "people"
-scope:
path: ""
type: "posts"
values:
layout: "post"
-scope:
path: ""
values:
layout: "default"